name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Init environment 
        uses: ./.github/actions/init-environment 
      - name: Run unit tests
        run: make test/unit
  test-bare:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Init environment 
        uses: ./.github/actions/init-bare-environment 
      - name: Run unit tests
        run: uv run pytest -n auto tests/unit/structures
  test-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4
      - name: Init environment 
        uses: ./.github/actions/init-environment
      - name: Run unit tests
        # TODO: make test/unit fails with the following error:
        # process_begin: CreateProcess(NULL, uv run pytest -n auto tests/unit, ...) failed.
        # make (e=2): The system cannot find the file specified.
        # make: *** [Makefile:24: test/unit] Error 2
        run: uv run pytest -n auto tests/unit
